//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDResearchLabFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResearchProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResearchProject()
        {
            this.LabAnnouncements = new HashSet<LabAnnouncement>();
            this.Publications = new HashSet<Publication>();
        }
    
        public int ResearchProjectsID { get; set; }
        public string Running { get; set; }
        public string Completed { get; set; }
        public Nullable<int> LabMembersID { get; set; }
        public Nullable<int> PublicationsID { get; set; }
        public string Descrptn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabAnnouncement> LabAnnouncements { get; set; }
        public virtual LabMember LabMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Publication> Publications { get; set; }
        public virtual Publication Publication { get; set; }
    }
}
